version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - VITE_WALLET_CONNECT_ID=${VITE_WALLET_CONNECT_ID}
      - VITE_ARKEO_ENDPOINT_REST=${VITE_ARKEO_ENDPOINT_REST}
      - VITE_ARKEO_ENDPOINT_RPC=${VITE_ARKEO_ENDPOINT_RPC}  
      - VITE_THORCHAIN_SERVER=${VITE_THORCHAIN_SERVER}
      - VITE_IS_TESTNET=${VITE_IS_TESTNET}

    restart: unless-stopped

